name = "webapp"
compatibility_date = "2025-11-20"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "webapp-production"
database_id = "a4c8c93c-0ab5-4150-9663-299d77636933"
